import Head from "next/head";
import type { NextPage } from "next";
import { dehydrate, QueryClient } from "react-query";

import LayoutArea from "@modules/_core/components/layout/LayoutArea";
import { fetchPokemon } from "@utils/api/rest/raw/module1";
import BannerArea from "@modules/home/Banner/BannerArea";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LayoutArea>
       <BannerArea/>
      </LayoutArea>
    </>
  );
};
export default Home;
// export async function getServerSideProps() {
export async function getStaticProps() {
  const queryClient = new QueryClient();
  await queryClient.prefetchQuery("pokemon", fetchPokemon);
  // will be fetched anf kept in cache, when call from client site will be available for initial render
  // will need to provide same key and function on client side as well
  return {
    props: {
      dehydratedState: dehydrate(queryClient),
    },
  };
}
